const technicalHtml = /*html*/ 
`<div class="uneditable">
<div class="uneditable">
<div class="WordSection1">
<p class="MsoNormal" style="margin-right: 31.7pt;"><span class="editable" lang="EN-GB" style="font-size: 10pt; color: black; ">[date]</span></p>
<p class="MsoNormal" style="margin-right: 31.7pt;"><span class="editable" lang="EN-GB" style="font-size: 10pt; ">[consultants name and address] </span></p>
<p class="MsoNormal" style="margin-right: 31.7pt;"><strong style="font-size: 10pt;"><span style="" class="editable">Attention: [ ]</span></strong></p>
<p class="MsoNormal" style="margin-right: 31.7pt;"><span class="editable" lang="EN-GB" style="font-size: 10pt; ">Dear Sirs,</span></p>
<p class="MsoNormal" style="margin-right: 31.7pt;"><u><span lang="EN-GB" style="font-size: 10pt; line-height: 98%; ; mso-fareast-theme-font: major-fareast; mso-bidi-theme-font: major-bidi; color: #2f5496; mso-themecolor: accent1; mso-themeshade: 191;">APPOINTMENT TO ACT AS A TECHNICAL CONSULTANT</span></u><span lang="EN-US" style="font-size: 10pt; mso-fareast-font-family: Carlito; mso-bidi-font-family: Carlito; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"> </span></p>
<p class="MsoNormal" style="margin-right: 31.7pt; text-align: justify;"><span class="editable" style="font-size: 10pt; text-align: justify;"><span style="">We refer to all correspondence between Infrastructure Credit Guarantee Company Limited (&ldquo;InfraCredit&rdquo; or the &ldquo;Company&rdquo;) and [Consultant&rsquo;s Name] (the &ldquo;Firm&rdquo;) in respect of the above subject matter and we are pleased to confirm the Firm&rsquo;s appointment as the consultant to provide technical due diligence to InfraCredit in connection with the proposed debt issuance programme for the financing of Energy Infrastructure projects (the &ldquo;Projects&rdquo;) by [Company] (or a Project SPV) to be guaranteed by InfraCredit (the &ldquo;Transaction&rdquo;).</span> </span><span style="font-size: 10pt; text-align: justify;"> This engagement letter confirms the terms of your engagement as due diligence consultant in connection with the</span><span style="letter-spacing: -0.45pt;"> </span><span style="font-size: 10pt; text-align: justify;">Transaction.</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: -33.75pt; line-height: 107%; mso-pagination: none; mso-list: l2 level1 lfo1; tab-stops: 55pt 55.05pt; text-autospace: none; margin: 0cm 0cm 0cm 55pt;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 11pt; line-height: 107%; mso-fareast- mso-bidi- mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">1.&nbsp; &nbsp; &nbsp; &nbsp; </span></span></strong><strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%;">SCOPE OF<span style="letter-spacing: -0.15pt;"> </span>WORK</span></strong></p>
<p class="MsoNormal" style="text-align: left; line-height: 107%; mso-pagination: none; tab-stops: 55pt 55.05pt; text-autospace: none; margin: 0cm 0cm 0cm 55pt;" align="left"><span class="editable" lang="EN-GB" style="font-size: 10pt; line-height: 107%; ">The scope of work will include to conduct technical and commercial review (Detail scope of work will be specified in the letter of engagement for specific transaction<strong>)</strong></span></p>
<p class="MsoNormal" style="text-align: left; text-indent: -33.75pt; line-height: 1.5; margin: 0cm 0cm 0cm 55pt;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 11pt; line-height: 107%; mso-fareast- mso-bidi- mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">2.&nbsp; &nbsp; &nbsp; &nbsp; </span></span></strong><strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%;">STAFFING AND RESOURCES</span></strong></p>
<p class="MsoNormal" style="text-indent: -36pt; line-height: 1.5; margin: 0cm 14.6pt 0cm 55pt; text-align: justify;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-fareast- mso-bidi- letter-spacing: -0.05pt; mso-font-width: 104%; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">2.1&nbsp; &nbsp; &nbsp; &nbsp;</span></span></strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%;">The Firm shall utilise a core team in the performance of this engagement. The team shall be led by<span style="letter-spacing: -0.4pt;"> <span style=""><strong>[</strong></span></span></span><span style=""><strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%; ; letter-spacing: -0.4pt; ">●</span></strong><strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%; letter-spacing: -0.4pt; ">] </span></strong></span><span lang="EN-GB" style="font-size: 10pt; line-height: 107%;">who<span style="letter-spacing: -0.45pt;"> </span>shall<span style="letter-spacing: -0.55pt;"> </span>have<span style="letter-spacing: -0.5pt;"> </span>the<span style="letter-spacing: -0.55pt;"> </span>overall<span style="letter-spacing: -0.6pt;"> </span>responsibility<span style="letter-spacing: -0.35pt;"> </span>of<span style="letter-spacing: -0.65pt;"> </span>managing<span style="letter-spacing: -0.45pt;"> </span>the<span style="letter-spacing: -0.5pt;"> </span>Firm&rsquo;s<span style="letter-spacing: -0.5pt;"> </span>role<span style="letter-spacing: -0.35pt;"> </span>in<span style="letter-spacing: -0.55pt;"> </span>relation to this Transaction.<span style="letter-spacing: 0.3pt;"> <span style=""><strong>[</strong></span></span></span><span style=""><strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%; ; letter-spacing: 0.3pt; ">●</span></strong><strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%; letter-spacing: 0.3pt; ">]</span></strong></span><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB" style="font-size: 10pt; line-height: 107%; color: red;"> </span></strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%;">will be responsible for overseeing the day-to-day tasks in respect of the Transaction. Other resources within the Firm will be utilised as and when the requisite expertise is<span style="letter-spacing: -0.25pt;"> </span>required.</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: -36pt; line-height: 107%; mso-pagination: none; mso-list: l2 level2 lfo1; tab-stops: 55.05pt; text-autospace: none; margin: 0cm 14.7pt 0cm 55pt;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-fareast- mso-bidi- letter-spacing: -0.05pt; mso-font-width: 104%; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">2.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></strong><span class="editable" lang="EN-GB" style="font-size: 10pt; line-height: 107%;">The persons who are listed below will be responsible for the day-today conduct of the Transaction:</span></p>
<table style="height: 148px; width: 80.328%; margin-left: 20px;">
<tbody>
<tr>
<td style="width: 49.0956%;"><span style="font-size: 10pt;"><strong>Name</strong></span></td>
<td style="width: 50.9044%;"><span style="font-size: 10pt;"><strong>Status</strong></span></td>
</tr>
<tr>
<td style="width: 49.0956%;">&nbsp;</td>
<td style="width: 50.9044%;">&nbsp;</td>
</tr>
<tr>
<td style="width: 49.0956%;">&nbsp;</td>
<td style="width: 50.9044%;">&nbsp;</td>
</tr>
<tr>
<td style="width: 49.0956%;">&nbsp;</td>
<td style="width: 50.9044%;">&nbsp;</td>
</tr>
<tr>
<td style="width: 49.0956%;">&nbsp;</td>
<td style="width: 50.9044%;">&nbsp;</td>
</tr>
</tbody>
</table>
<p class="MsoNormal" style="text-align: left; text-indent: -33.75pt; line-height: 107%; mso-pagination: none; mso-list: l2 level1 lfo1; tab-stops: 55pt 55.05pt; text-autospace: none; margin: 0cm 0cm 0cm 55pt;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 11pt; line-height: 107%; mso-fareast- mso-bidi- mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></strong><strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%;">FEE ARRANGEMENTS</span></strong></p>
<p class="MsoNormal" style="text-indent: -36pt; margin: 0cm 14.6pt 0cm 55pt; text-align: left;"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 10pt; mso-fareast- mso-bidi- letter-spacing: -0.05pt; mso-font-width: 104%; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">3.1&nbsp; &nbsp; &nbsp; &nbsp; </span></span></strong><span lang="EN-GB" style="font-size: 10pt;">The professional fees for providing the services set out in the Scope of Work shall be<strong style="mso-bidi-font-weight: normal;">&nbsp;</strong><span style="mso-bidi-font-weight: bold;"><strong><span style="">NGN [*] Million Naira</span> </strong> </span> broken down as indicated in the table below. The fees are net of all taxes (including any applicable withholding taxes or value added tax (VAT) and<span style="letter-spacing: 0.65pt;"> </span>expenses.</span></p>
<table style="height: 148px; width: 96.6538%;">
<tbody>
<tr>
<td style="width: 25.523%;"><span style="font-size: 10pt;"><strong>WORK PHASE</strong></span></td>
<td style="width: 24.9651%;"><span style="font-size: 10pt;"><strong>LUMP SUM FEES</strong></span></td>
<td style="width: 49.5119%;"><span style="font-size: 10pt;"><strong>PAYMENT TERMS</strong></span></td>
</tr>
<tr>
<td style="width: 25.523%;"><span style="font-size: 10pt;">Technical Due&nbsp;Diligence</span></td>
<td style="width: 24.9651%;"><span style="font-size: 10pt;"><strong>N&nbsp;</strong></span></td>
<td style="width: 49.5119%;">
<p><span style="font-size: 10pt;">60% of fees payable on engagement</span></p>
<p><span style="font-size: 10pt;">Balance of 40% payable upon submission of the final draft of the Due Diligence Report to InfraCredit.</span></p>
</td>
</tr>
</tbody>
</table>
<p class="MsoNormal" style="text-align: left; text-indent: -36pt; line-height: 107%; mso-pagination: none; mso-list: l2 level2 lfo1; tab-stops: 55.05pt; text-autospace: none; margin: 2.85pt 14.9pt 0cm 55pt;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-fareast- mso-bidi- letter-spacing: -0.05pt; mso-font-width: 104%; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">3.2&nbsp; &nbsp; &nbsp; &nbsp; </span></span></strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%; mso-font-width: 105%;">Reasonable out-of-pocket and receipted expenses incurred by your Firm as a direct result of performing the services hereunder will be borne by InfraCredit and charged at cost. InfraCredit&rsquo;s prior consent must be obtained in respect of expenses exceeding NGN50,000.00 (Fifty Thousand<span style="letter-spacing: 0.2pt;"> </span>Naira)</span><span lang="EN-GB" style="font-size: 10pt; line-height: 98%;">&nbsp;</span></p>
<p class="MsoNormal" style="text-indent: -36pt; line-height: 98%; mso-pagination: none; tab-stops: 55.05pt; text-autospace: none; margin: 0cm 14.7pt 12pt 54pt;"><strong><span lang="EN-GB" style="font-size: 10pt; line-height: 98%;">3.3</span></strong><span lang="EN-GB" style="font-size: 10pt; line-height: 98%;"><span style="mso-tab-count: 1;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>All invoices, accounts and requests for payment are expected to be met within fifteen (15) days of the<span style="letter-spacing: -0.15pt;"> </span>invoice/request.</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: -33.75pt; line-height: 107%; mso-pagination: none; mso-list: l2 level1 lfo1; tab-stops: 55.05pt; text-autospace: none; margin: 0cm 0cm 0cm 55pt;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 11pt; line-height: 107%; mso-fareast- mso-bidi- mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">4.&nbsp; &nbsp; &nbsp; &nbsp; </span></span></strong><strong><span class="editable" lang="EN-GB" style="font-size: 10pt; line-height: 107%;">DURATION</span></strong></p>
<p class="MsoNormal" style="mso-pagination: none; tab-stops: 55.05pt; text-autospace: none; margin: 0cm 0cm 0cm 55pt;"><span lang="EN-GB" style="font-size: 10pt; ">Duration&nbsp;</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: -33.75pt; line-height: 107%; mso-pagination: none; mso-list: l2 level1 lfo1; tab-stops: 55.05pt; text-autospace: none; margin: 0cm 0cm 0cm 55pt;" align="left"><strong><span lang="EN-US" style="font-size: 11pt; line-height: 107%; mso-fareast- mso-bidi- mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">5.&nbsp; &nbsp; &nbsp; &nbsp; COMPLIANCE COVENANTS</span></span></strong></p>
<p class="MsoNormal" style="mso-add-space: auto; line-height: 98%; mso-pagination: none; tab-stops: 55.05pt; text-autospace: none; margin: 0cm 14.7pt 0cm 55pt;"><span lang="EN-GB" style="font-size: 10pt; line-height: 98%; mso-bidi-font-weight: bold; mso-bidi-font-style: italic;">The Firm undertakes that it shall, and shall procure that each of its employees, directors, personnel and affiliates shall comply with the Compliance Covenants set out in Schedule 1 to this Letter.</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: -33.75pt; line-height: 107%; mso-pagination: none; mso-list: l2 level1 lfo1; tab-stops: 55pt 55.05pt; text-autospace: none; margin: 0cm 0cm 0cm 55pt;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 11pt; line-height: 107%; mso-fareast- mso-bidi- mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">6.&nbsp; &nbsp; &nbsp; &nbsp; </span></span></strong><strong><span class="editable" lang="EN-GB" style="font-size: 10pt; line-height: 107%;">CONTACT ADDRESS, TELEPHONE AND E-MAIL</span></strong></p>
<p class="MsoNormal" style="margin: 0.05pt 67.85pt 12pt 55pt;"><span class="editable" lang="EN-GB" style="font-size: 10pt; ">Name:<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> </span></p>
<p class="MsoNormal" style="tab-stops: 127pt; margin: 0.05pt 67.85pt 12pt 55pt;"><span class="editable" lang="EN-GB" style="font-size: 10pt; ">Address: <span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;</span></span></p>
<p class="MsoNormal" style="line-height: 98%; tab-stops: 127pt; margin: 0.1pt 240.95pt 12pt 55pt;"><span class="editable" lang="EN-GB" style="font-size: 10pt; line-height: 98%; ">E-mail:<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></p>
<p class="MsoNormal" style="line-height: 98%; tab-stops: 127pt; margin: 0.1pt 240.95pt 12pt 55pt;"><span class="editable" lang="EN-GB" style="font-size: 10pt; line-height: 98%; ">Mobile:</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: -33.75pt; line-height: 107%; mso-pagination: none; mso-list: l2 level1 lfo1; tab-stops: 55pt 55.05pt; text-autospace: none; margin: 0cm 0cm 0cm 55pt;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 11pt; line-height: 107%; mso-fareast- mso-bidi- mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">7.&nbsp; &nbsp; &nbsp; &nbsp; </span></span></strong><strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%;">CONFIDENTIALITY</span></strong></p>
<p class="MsoNormal" style="margin: 1.95pt 14.8pt 12pt 55pt; text-align: justify;"><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">The Firm agrees to keep confidential all information made available in connection with the services performed hereunder and undertakes that any information provided will be used solely for the purpose of providing services to InfraCredit. Such information may not be photocopied, reproduced or distributed to persons outside the Firm at any time without InfraCredit&rsquo;s prior written consent. Information will be made known to personnel within the Firm only on a &ldquo;need to<span style="letter-spacing: -0.1pt;"> </span>know&rdquo;<span style="letter-spacing: -0.1pt;"> </span>basis,<span style="letter-spacing: -0.15pt;"> </span>and<span style="letter-spacing: -0.2pt;"> </span>the<span style="letter-spacing: -0.1pt;"> </span>Firm<span style="letter-spacing: -0.15pt;"> </span>is<span style="letter-spacing: -0.15pt;"> </span>responsible<span style="letter-spacing: -0.05pt;"> </span>for<span style="letter-spacing: -0.15pt;"> </span>ensuring<span style="letter-spacing: -0.15pt;"> </span>that<span style="letter-spacing: -0.15pt;"> </span>the<span style="letter-spacing: -0.15pt;"> </span>foregoing<span style="letter-spacing: -0.15pt;"> </span>obligations<span style="letter-spacing: -0.15pt;"> </span>are<span style="letter-spacing: -0.1pt;"> </span>strictly observed by the Firm&rsquo;s<span style="letter-spacing: -0.45pt;"> </span>personnel.</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: -33.75pt; line-height: 107%; mso-pagination: none; mso-list: l2 level1 lfo1; tab-stops: 55pt 55.05pt; text-autospace: none; margin: 0cm 0cm 0cm 55pt;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 11pt; line-height: 107%; mso-fareast- mso-bidi- mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">8.&nbsp; &nbsp; &nbsp; &nbsp; </span></span></strong><strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%;">TERMINATION</span></strong></p>
<p class="MsoNormal" style="text-indent: -33.75pt; margin: 0.05pt 0cm 12pt 55pt; text-align: justify;"><span style="mso-bookmark: _Hlk62664861;"><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">8.1<span style="mso-tab-count: 1;">&nbsp; &nbsp; &nbsp; &nbsp;</span>InfraCredit is entitled to terminate this engagement if the Firm culpably fails to meet its contractual obligations or if the performance of its services is not in compliance with this Engagement Letter, or the services are not performed in a timely fashion. In this case, the Firm is solely entitled to demand the agreed remuneration for the services already performed until the date of termination but not yet remunerated. InfraCredit shall be entitled to demand compensation for the direct damage caused by this default.</span></span></p>
<p class="MsoNormal" style="text-indent: -36pt; margin: 0.05pt 0cm 12pt 55pt; text-align: justify;"><span style="mso-bookmark: _Hlk62664861;"><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">8.2<span style="mso-tab-count: 1;">&nbsp; &nbsp; &nbsp;</span>The Firm may terminate this Contract if InfraCredit does not pay any amounts due and payable to it under this engagement or does not make payment in a timely fashion. The Firm shall be entitled to demand the agreed remuneration for the services performed until the date of termination but not yet remunerated.</span></span></p>
<p class="MsoNormal" style="text-indent: -36pt; margin: 0.05pt 0cm 12pt 55pt; text-align: justify;"><span style="mso-bookmark: _Hlk62664861;"><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">8.3<span style="mso-tab-count: 1;">&nbsp; &nbsp; &nbsp; </span>Before either party serves a notice of termination, the other party is to be served notice of breach of its contractual obligations and to be granted a grace period of at least 30 days to remedy this breach. </span></span></p>
<p class="MsoNormal" style="margin: 0.05pt 0cm 12pt 55pt; text-indent: -36pt; text-align: justify;"><span style="mso-bookmark: _Hlk62664861;"><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">8.4<span style="mso-tab-count: 1;">&nbsp; &nbsp; &nbsp; </span>InfraCredit may suspend or terminate this Contract after serving written notice of at least 30 days without stating reasons. In the event of suspension or termination, the Firm is obliged to immediately take measures to limit damages. On termination, all previously created drafts, reports or other documents or such that are to be created by the termination date are to be passed on to InfraCredit.</span></span></p>
<p class="MsoNormal" style="text-align: left; text-indent: -33.75pt; line-height: 107%; mso-pagination: none; mso-list: l2 level1 lfo1; tab-stops: 55pt 55.05pt; text-autospace: none; margin: 0cm 0cm 0cm 55pt;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-US" style="font-size: 11pt; line-height: 107%; mso-fareast- mso-bidi- mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="mso-list: Ignore;">9.&nbsp; &nbsp; &nbsp; &nbsp; </span></span></strong><strong><span lang="EN-GB" style="font-size: 10pt; line-height: 107%;">COMMUNICATIONS</span></strong></p>
<p class="MsoNormal" style="margin: 0cm 14.65pt 12pt 55pt; text-align: justify;"><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">All correspondence should be marked for the attention of Mr. Chinua Azubike at cazubike@infracredit.ng </span> <span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">and for the attention of <span style="">Adesola Abidoun&nbsp;</span></span><span class="editable"><span style="font-size: 10pt; ">at aabiodun@infracredit.ng</span></span><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">, in charge of this Transaction. While you are working on this Transaction, you may be in contact with other InfraCredit staff members, in addition to us. For coordination purposes, it is indispensable<span style="letter-spacing: -0.15pt;"> </span>that<span style="letter-spacing: -0.35pt;"> </span>we<span style="letter-spacing: -0.2pt;"> </span>are<span style="letter-spacing: -0.3pt;"> </span>kept<span style="letter-spacing: -0.1pt;"> </span>informed<span style="letter-spacing: -0.25pt;"> </span>of<span style="letter-spacing: -0.25pt;"> </span>these<span style="letter-spacing: -0.25pt;"> </span>contacts,<span style="letter-spacing: -0.2pt;"> </span>any<span style="letter-spacing: -0.2pt;"> </span>proposed<span style="letter-spacing: -0.35pt;"> </span>meetings<span style="letter-spacing: -0.15pt;"> </span>that<span style="letter-spacing: -0.25pt;"> </span>you<span style="letter-spacing: -0.25pt;"> </span>have been requested to attend and any oral advice<span style="letter-spacing: -0.35pt;"> </span>given.</span></p>
<p class="MsoNormal" style="margin: 0cm 14.75pt 12pt 54pt; text-align: justify;" align="left"><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">This letter may be executed in separate counterparts, each of which shall be deemed an original instrument. This letter may only be amended in writing signed on behalf of InfraCredit and your Firm.</span></p>
</div>
<p class="MsoNormal pdf-pagebreak-before" style="margin: 0.05pt 0cm 12pt 5.45pt;"><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">Yours faithfully,</span></p>
<p class="MsoNormal" style="margin: 0.05pt 0cm 12pt 5.45pt;"><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">For: Infrastructure Credit Guarantee Company Limited</span></p>
<p class="MsoNormal" style="margin-top: 0.05pt;">&nbsp;</p>
<p class="MsoNormal"><span lang="EN-GB" style="font-size: 10pt; margin-bottom: -20px; mso-fareast-theme-font: major-fareast; mso-bidi-theme-font: major-bidi; color: #2f5496; mso-themecolor: accent1; mso-themeshade: 191;">Mr. Chinua Azubike</span></p>
<p class="MsoNormal" style="margin: 0.05pt 0cm 12pt 5.45pt;"><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">Chief Executive Officer</span></p>
<p class="MsoNormal" style="line-height: 99%; margin: 0.05pt 14.75pt 0pt 5.4pt;"><span lang="EN-GB" style="font-size: 10pt; line-height: 99%; mso-bidi-font-family: 'Simplified Arabic';">&nbsp;</span></p>
<p class="MsoNormal" style="line-height: 99%; margin: 0.05pt 14.75pt 12pt 5.4pt;"><span lang="EN-GB" style="font-size: 10pt; line-height: 99%; mso-bidi-font-family: 'Simplified Arabic';">We agree to act as Consultant with respect to the above-captioned Transaction and to be bound by the terms stated herein and entered into between us and InfraCredit.</span></p>
<p class="MsoNormal" style="margin-top: 0.05pt;"><span lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0cm 292.05pt 12pt 5.45pt;"><span class="editable" lang="EN-GB" style="font-size: 10pt; mso-bidi-font-family: 'Simplified Arabic';">Signed for and on behalf of <span style="">[</span></span><span style=""><span lang="EN-GB" style="font-size: 10pt; ; ">●</span><span lang="EN-GB" style="font-size: 10pt; ">]</span></span></p>
<p class="MsoNormal" style="line-height: 152%; tab-stops: 55pt; margin: 0cm 292.05pt 12pt 5.45pt;"><span class="editable" lang="EN-GB" style="font-size: 10pt; line-height: 152%; letter-spacing: -0.05pt; ">Signature</span></p>
<p class="MsoNormal" style="margin: 0cm 292.05pt 12pt 5.45pt; line-height: 152%; tab-stops: 55pt;"><span style=""><span class="editable" lang="EN-GB" style="font-size: 10pt; line-height: 152%; ">Name<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> </span></span></p>
<p class="MsoNormal" style="tab-stops: 55pt; margin: 0cm 292.05pt 12pt 5.45pt;"><span class="editable" lang="EN-GB" style="font-size: 10pt; ">Title<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> </span></p>
<p class="MsoNormal " style="margin: 0cm 292.05pt 12pt 5.45pt; tab-stops: 56.55pt;"><span class="editable" lang="EN-GB" style="font-size: 10pt; ">Date<span style="mso-tab-count: 1;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></p>
<p class="MsoNormal pdf-pagebreak-before"><span lang="EN-GB" style="font-size: 10pt;">&nbsp;</span></p>
<p class="MsoNormal"><strong><span lang="EN-GB" style="font-size: 10pt;">Schedule 1 - </span></strong><strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">&ndash; Compliance Covenants</span></strong></p>
<p class="MsoNormal"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">&nbsp;</span></p>
<ol style="margin-top: 0cm;" start="1" type="1">
<li class="MsoNormal" style="margin-bottom: 0cm; text-align: left; line-height: 107%; mso-list: l3 level1 lfo2;"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US;">DEFINITIONS</span></u></strong></li>
</ol>
<p class="MsoNormal"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Coercive Practice</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">:<span style="mso-tab-count: 1;">&nbsp; t</span>he impairing or harming, or threatening to impair or harm, directly or indirectly, any person or the property of the person with a view to influencing improperly the actions of a person.</span></p>
<p class="MsoNormal"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Collusive Practice</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: an arrangement between two or more persons designed to achieve an improper purpose, including to influence improperly the actions of another person.</span></p>
<p class="MsoNormal" style="text-align: justify;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Corrupt Practice</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: the promising, offering, giving, making, insisting on, receiving, accepting or soliciting, directly or indirectly, of any illegal payment or undue advantage of any nature, to or by any person, with the intention of influencing the actions of any person or causing any person to refrain from any action.</span></p>
<p class="MsoNormal" style="text-align: justify;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Designated Categories of Offences</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: the following categories of offences as defined by the FATF Recommendations and the respective interpretative note: participation in an organised criminal group and racketeering; terrorism, including financing of terrorism; trafficking in human beings and migrant smuggling; sexual exploitation, including sexual exploitation of children; illicit trafficking in narcotic drugs and psychotropic substances; illicit arms trafficking; illicit trafficking in stolen and other goods; corruption and bribery; fraud; counterfeiting currency; counterfeiting and piracy of products; environmental crime; murder, grievous bodily injury; kidnapping, illegal restraint and hostage-taking; robbery or theft; smuggling (including in relation to customs and excise duties and taxes); tax crimes (related to direct taxes and indirect taxes); extortion; forgery; piracy; insider trading and market manipulation.</span></p>
<p class="MsoNormal" style="text-align: justify;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">FATF Recommendations</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: such recommendations as defined from time to time by the Financial Action Task Force (FATF). FATF is the inter-governmental body whose purpose is the development and promotion of national and international policies to combat money laundering and the financing of terrorism.</span></p>
<p class="MsoNormal"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Fraudulent Practice</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: any action or omission, including misrepresentation that knowingly or recklessly misleads, or attempts to mislead, a person to obtain a financial benefit or to avoid an obligation.</span></p>
<p class="MsoNormal"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Illicit Origin</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: the origin of funds obtained through </span></p>
<p class="MsoNormal"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">a)<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>any offence listed in the Designated Categories of Offences;</span></p>
<p class="MsoNormal"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">b)<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>any Corrupt Practice; </span></p>
<p class="MsoNormal"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">c)<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>any Fraudulent Practice; or</span></p>
<p class="MsoNormal"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">d)<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>money laundering.</span></p>
<p class="MsoNormal" style="text-align: justify;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Obstructive Practice</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: (i) deliberately destroying, falsifying, altering or concealing evidence material to the investigation or the making of false statements to investigators, in order to materially impede an official investigation into allegations of a Corrupt Practice, Fraudulent Practice, Coercive Practice or Collusive Practice, or threatening, harassing or intimidating any person to prevent it from disclosing its knowledge of matters relevant to the investigation or from pursuing the investigation, or (ii) any act intended to materially impede the exercise of InfraCredit's access to contractually required information in connection with an official investigation into allegations of a Corrupt Practice, Fraudulent Practice, Coercive Practice or Collusive Practice.</span></p>
<p class="MsoNormal"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Person</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: any natural person, legal entity, partnership or unincorporated association.</span></p>
<p class="MsoNormal" style="text-align: justify;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Sanctionable Practice</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: any Coercive Practice, Collusive Practice, Corrupt Practice, Fraudulent Practice or Obstructive Practice (as such terms are defined herein), which (i) is unlawful under Nigerian or other applicable law, and (ii) which has, or potentially could have, a material legal or reputational effect on this Agreement between the Firm and InfraCredit or its implementation.</span></p>
<p class="MsoNormal" style="text-align: justify;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Sanctioning Body</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: any of the United Nations Security Council, the European Union and the Federal Republic of Germany.</span></p>
<p class="MsoNormal" style="text-align: justify;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Sanctions</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: the economic, financial or trade sanctions laws, regulations, embargoes or restrictive measures administered, enacted or enforced by any Sanctioning Body.</span></p>
<p class="MsoNormal" style="text-align: justify;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">Sanctions List</span></strong><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">: any list of specially designated persons, groups or entities which are subject to Sanctions, as issued by any Sanctioning Body.</span></p>
<ol style="margin-top: 0cm;" start="2" type="1">
<li class="MsoNormal" style="margin-bottom: 0cm; text-align: left; line-height: 107%; mso-list: l3 level1 lfo2;"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US;">INFORMATION UNDERTAKING</span></u></strong></li>
</ol>
<p class="MsoNormal" style="padding-left: 40px;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">The Firm shall:</span></p>
<ol type="a">
<li style="text-align: justify; font-size: 10pt;"><span style="font-size: 10pt;">promptly make available to InfraCredit on demand all relevant "know your customer" or similar information about the Firm or any of its members as InfraCredit may request;</span></li>
<li style="text-align: justify; font-size: 10pt;"><span style="font-size: 10pt;">promptly furnish to InfraCredit on demand all information and documents of the Firm and its (sub)contracting and other related parties which InfraCredit requires to fulfil its obligations to prevent any Sanctionable Practice, money laundering or terrorism financing as well as for the continuous monitoring of the business relationship with the Firm which is necessary for this purpose;</span></li>
<li style="text-align: justify; font-size: 10pt;"><span style="font-size: 10pt;">inform InfraCredit, promptly and of its own accord, as soon as it becomes aware of or suspects, any Sanctionable Practice, act of money laundering or/and terrorism financing by the Firm or any of its members;</span></li>
<li style="text-align: justify; font-size: 10pt;"><span style="font-size: 10pt;">furnish to InfraCredit any and all such information and reports on the Services and their further progress as InfraCredit may request for the purposes of this Schedule;</span></li>
<li style="text-align: justify; font-size: 10pt;"><span style="font-size: 10pt;">enable InfraCredit and its agents at any time to inspect all other documentation of the Firm and its (sub)contracting and other related parties relevant to the execution of the Services for the purposes of this Schedule;</span></li>
<li style="text-align: justify; font-size: 10pt;"><span style="font-size: 10pt;">inform InfraCredit, promptly and of its own accord, of any event which results in the Firm or any of its members, being or becoming a specially designated national, blocked person or entity maintained on any Sanctions List.</span></li>
</ol>
<ol style="margin-top: 0cm;" start="3" type="1">
<li class="MsoNormal" style="margin-bottom: 0cm; text-align: left; line-height: 107%; mso-list: l3 level1 lfo2;"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US;">REPRESENTATIONS AND WARRANTIES</span></u></strong></li>
</ol>
<p class="MsoNormal" style="padding-left: 40px;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">With regard to Nigerian law, the Firm represents and warrants that the following is true and correct:</span></p>
<ol type="a">
<li style="text-align: justify; font-size: 10pt;"><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US;">In entering into and implementing this Agreement, the Firm acts in its own name and for its own account.</span></li>
<li style="text-align: justify; font-size: 10pt;"><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US;">To the best of its knowledge and only in relation to the members, the funds invested in the Firm are not of Illicit Origin.</span></li>
<li style="text-align: justify; font-size: 10pt;"><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US;">None of the Firm or any other person acting on its behalf has committed or is engaged in any Sanctionable Practice, money laundering or financing of terrorism.</span></li>
<li style="text-align: justify; font-size: 10pt;"><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US;">The Firm has not (i) entered into any business relationship with specially designated nationals, blocked persons or entities maintained on any Sanctions List; or (ii) engaged in any other activity that would constitute a breach of Sanctions.</span></li>
</ol>
<ol style="margin-top: 0cm;" start="4" type="1">
<li class="MsoNormal" style="margin-bottom: 0cm; text-align: left; line-height: 107%; mso-list: l3 level1 lfo2;"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US;">POSITIVE UNDERTAKINGS</span></u></strong></li>
</ol>
<p class="MsoNormal" style="padding-left: 40px;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">The Firm undertakes:</span></p>
<ol type="a">
<li style="text-align: justify; font-size: 10pt;"><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US;">to fully comply with anti-money laundering and terrorism financing standards in accordance with the FATF Recommendations, and implement, maintain and, if necessary, improve its internal standards and guidelines (including without limitation in relation to customer due diligence) appropriate to avoid any Sanctionable Practice, act of money laundering or financing of terrorism; and</span></li>
<li style="text-align: justify; font-size: 10pt;"><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US;">as soon as the Firm or InfraCredit becomes aware of or suspects any Sanctionable Practice, act of money laundering or financing of terrorism, to fully cooperate with the Firm and its agents, in determining whether such compliance incident has occurred. In particular, the Firm shall respond promptly and in reasonable detail to any notice from InfraCredit and shall furnish documentary support for such response upon InfraCredit's request.</span>&nbsp; &nbsp;</li>
</ol>
<ol style="margin-top: 0cm;" start="5" type="1">
<li class="MsoNormal" style="margin-bottom: 0cm; text-align: left; line-height: 107%; mso-list: l3 level1 lfo2;"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-US" style="font-size: 10pt; line-height: 107%; mso-ansi-language: EN-US;">NEGATIVE UNDERTAKINGS</span></u></strong></li>
</ol>
<p class="MsoNormal" style="padding-left: 40px;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">The Firm undertakes:</span></p>
<ol type="a">
<li style="text-align: justify; font-size: 10pt;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">to ensure that its equity and other funds it invests will not be of Illicit Origin;</span></li>
<li style="text-align: justify; font-size: 10pt;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">to ensure that its business will not give rise to any Sanctionable Practice, money laundering or financing of terrorism; and</span></li>
<li style="text-align: justify; font-size: 10pt;"><span lang="EN-US" style="font-size: 10pt; mso-ansi-language: EN-US;">not to enter into or continue any business relationship with specially designated nationals, blocked persons or entities maintained on any Sanctions List and not to engage in any other activity that would constitute a breach of Sanction.</span></li>
</ol>
</div>`;

export default technicalHtml;
